/**
 * TypesGenerator — Generates Types.luau content from the service and controller registries.
 */

import { serviceRegistry, ServiceInfo, ServiceMethod } from '../registry/ServiceRegistry';
import { controllerRegistry, ControllerInfo } from '../registry/ControllerRegistry';

function formatParams(params: string[]): string {
  if (params.length === 0) return '';
  return params.map(p => `${p}: any`).join(', ');
}

function generateServiceType(service: ServiceInfo): string {
  const lines: string[] = [];
  lines.push(`export type ${service.name} = {`);

  for (const method of service.methods) {
    const params = formatParams(method.params);
    const ret = method.returnType ? method.returnType : '()';
    lines.push(`\t${method.name}: (${params}) -> ${ret},`);
  }

  for (const method of service.clientMethods) {
    const params = formatParams(method.params);
    const ret = method.returnType ? method.returnType : '()';
    lines.push(`\t${method.name}: (${params}) -> ${ret},`);
  }

  lines.push('}');
  return lines.join('\n');
}

function generateServiceClientType(service: ServiceInfo): string {
  const lines: string[] = [];
  lines.push(`export type ${service.name}Client = {`);

  for (const method of service.clientMethods) {
    // Client proxy: player arg removed, return wrapped in Promise
    const params = formatParams(method.params);
    const ret = method.returnType ? `Promise<${method.returnType}>` : 'Promise<()>';
    lines.push(`\t${method.name}: (${params}) -> ${ret},`);
  }

  for (const event of service.netEvents) {
    lines.push(`\t${event.name}: Signal<...any>,`);
  }

  lines.push('}');
  return lines.join('\n');
}

function generateControllerType(controller: ControllerInfo): string {
  const lines: string[] = [];
  lines.push(`export type ${controller.name} = {`);

  for (const method of controller.methods) {
    const params = formatParams(method.params);
    const ret = method.returnType ? method.returnType : '()';
    lines.push(`\t${method.name}: (${params}) -> ${ret},`);
  }

  lines.push('}');
  return lines.join('\n');
}

export function generateTypes(): string {
  const timestamp = new Date().toISOString();
  const lines: string[] = [];

  lines.push('-- AUTOGENERATED BY KORE EXTENSION. DO NOT EDIT MANUALLY.');
  lines.push(`-- Last updated: ${timestamp}`);
  lines.push('');

  // Core framework types
  lines.push('export type ContextType = {');
  lines.push('\tLog: any,');
  lines.push('\tKore: any,');
  lines.push('\tConfig: { [string]: any }?,');
  lines.push('}');
  lines.push('');

  lines.push('export type ServiceType = {');
  lines.push('\tName: string,');
  lines.push('\tDependencies: { string }?,');
  lines.push('\tConfig: { [string]: any }?,');
  lines.push('\tClient: { [string]: any }?,');
  lines.push('\tInit: ((self: any, ctx: ContextType) -> ())?,');
  lines.push('\tStart: ((self: any, ctx: ContextType) -> ())?,');
  lines.push('\tDestroy: ((self: any) -> ())?,');
  lines.push('\tJanitor: any,');
  lines.push('\tLog: any,');
  lines.push('}');
  lines.push('');

  lines.push('export type ControllerType = {');
  lines.push('\tName: string,');
  lines.push('\tDependencies: { string }?,');
  lines.push('\tConfig: { [string]: any }?,');
  lines.push('\tInit: ((self: any, ctx: ContextType) -> ())?,');
  lines.push('\tStart: ((self: any, ctx: ContextType) -> ())?,');
  lines.push('\tDestroy: ((self: any) -> ())?,');
  lines.push('\tJanitor: any,');
  lines.push('\tLog: any,');
  lines.push('}');
  lines.push('');

  lines.push('export type MiddlewareFn = (player: Player, ...any) -> ...any');
  lines.push('export type NetEventType = any');
  lines.push('');

  lines.push('export type SignalType<T...> = {');
  lines.push('\tConnect: (self: any, fn: (T...) -> ()) -> any,');
  lines.push('\tOnce: (self: any, fn: (T...) -> ()) -> any,');
  lines.push('\tWait: (self: any) -> T...,');
  lines.push('\tFire: (self: any, T...) -> (),');
  lines.push('\tDisconnectAll: (self: any) -> (),');
  lines.push('}');
  lines.push('');

  // Generated service types
  const services = serviceRegistry.getAll();
  for (const service of services) {
    lines.push(generateServiceType(service));
    lines.push('');
    lines.push(generateServiceClientType(service));
    lines.push('');
  }

  // Generated controller types
  const controllers = controllerRegistry.getAll();
  for (const controller of controllers) {
    lines.push(generateControllerType(controller));
    lines.push('');
  }

  lines.push('return {}');
  lines.push('');

  return lines.join('\n');
}
